'use strict';"strict mode";
const body=document.querySelector("body"),ladowanie=document.getElementById("ladowanie"),tytul_portalu=document.getElementById("tytul_portalu"),lupka=document.getElementById("lupka"),wyszukiwarka=document.getElementById("wyszukiwarka"),powiad_przycisk=document.getElementById("powiad_przycisk"),powiadomienia=document.querySelector(".powiadomienia"),powiad=document.getElementById("powiad"),pilne_przycisk=document.getElementById("pilne_przycisk"),pilne_wiad=document.getElementById("pilne_wiad"),wiad_przycisk=
document.getElementById("wiad_przycisk"),wiadomosci=document.getElementById("wiadomosci");let aktywny_dymek=null,aktywnyprzycik=null;const wiadomosci_tel=document.getElementById("wiadomosci_tel"),pow_tel=document.getElementById("pow_tel"),wyszukaj=document.getElementById("wyszukaj");let szukanie=!1,szukanie_live=!1,czy_wstawiano_post=!1,licznik_zdjec=0;(function(){window.onload=()=>{renderuj_nawigacje();renderuj_glowne();prawa_burta();body.removeChild(ladowanie);nowe_posty()}})();
function przelodwanie(){document.location.reload()}
function renderuj_nawigacje(){let e=document.createElement("nav"),f=document.createElement("div");f.className="menu";var d=document.createElement("header");d.id="tytul_portalu";d.innerHTML="<h1>Pixi</h1>";d.addEventListener("click",przelodwanie);f.appendChild(d);d=document.createElement("div");d.classList="wyszukaj i";var a=document.createElement("form");a.setAttribute("method","POST");a.className="i";var c=document.createElement("input");c.setAttribute("type","text");c.className="b";c.setAttribute("name",
"wyszukiwarka");c.id="wyszukiwarka";c.setAttribute("placeholder","Szukaj w pixi");c.addEventListener("focus",()=>{szukanie_live||(943<=window.innerWidth&&(szukanie_live?"":pole_wyszukiwania()),szukanie_live=!0)});a.appendChild(c);d.appendChild(a);f.appendChild(d);a=document.createElement("button");a.id="lupka";a.innerHTML="&#128270;";d.appendChild(a);d=document.createElement("div");d.className="telefon";a=document.createElement("button");a.id="wiadomosci_tel";a.className="wiadomosci_ikonka";a.setAttribute("alt",
"wiadomosci");a.innerHTML="&#128232;";c=document.createElement("div");c.className="licznik_menu";c.innerText="488";a.appendChild(c);d.appendChild(a);a=document.createElement("div");a.id="pow_tel";a.style.left="48%";a.className="wiadomosci_ikonka";a.innerHTML="&#128240;";c=document.createElement("div");c.className="licznik_menu";c.innerText="488";a.appendChild(c);d.appendChild(a);a=document.createElement("div");a.appendChild(document.createElement("div"));a.appendChild(document.createElement("div"));
a.appendChild(document.createElement("div"));a.id="hamburger";a.addEventListener("click",()=>{document.querySelector(".komputer").classList.toggle("widocznoscz")});d.appendChild(a);f.appendChild(d);d=document.createElement("div");d.className="komputer";a=document.createElement("div");a.className="menu_opcje";c=document.createElement("div");c.innerHTML="X";c.style.background="none";c.style.fontSize="48px";c.style.margin="24px";c.className="zamknij";c.addEventListener("click",()=>{document.querySelector(".komputer").classList.toggle("widocznoscz")});
a.appendChild(c);d.appendChild(a);f.appendChild(d);e.appendChild(f);body.appendChild(e);nowy_dym_wysz()}
function renderuj_menu(){let e=document.querySelector(".menu_opcje");[["aktywny_przycisk","Strona g\u0142\u00f3wna"],["powiad_przycisk","Powiadomienia","powiadomienia"],["wiad_przycisk","Wiadomo\u015bci","wiadomosci"],["dodawanie_posta","Dodaj artyku\u0142"],[" ","M\u00f3j profil"],[" ","Ustawienia"],[" ","Wi\u0119cej"],[" ","Wyloguj"]].forEach(f=>{const d=document.createElement("button");d.id=f[0];d.innerText=f[1];3<=f.length&&f[2]&&(zmieniajdymki(d,document.getElementById(f[2]),"#"+f[2]+" h2 button"),
f=document.createElement("div"),f.className="licznik_menu",f.innerText="488",d.appendChild(f));e.appendChild(d)});document.getElementById("dodawanie_posta").addEventListener("click",renderuj_wstawianie_nowy_post)}
function nowy_dym_wysz(){[["powiadomienia","powiad","Moje powiadomienia","pow_tel"],["wiadomosci","pilne_wiadom","Wiadomo\u015bci","wiadomosci_tel"],["wyszukaj","wynik_wyszuk","Wyniki wyszukiwania","lupka"]].forEach(e=>{let f=body.appendChild(document.createElement("aside")),d=document.createElement("div");d.id=e[0];d.classList="powiadomienia";var a=document.createElement("h2");"wyszukaj"!=e[0]?a.innerText=e[2]+" :":(a.className="border_none",d.innerHTML='\n        <form method="POST" class="i"><input type="text" class="wyszukuwanie" name="wyszukiwarka" id="wyszukiwark" placeholder="Szukaj w pixi"></form>\n        ');
var c=document.createElement("button");c.innerText="X";a.appendChild(c);d.appendChild(a);a=document.createElement("div");a.classList="powiad";a.id=e[1];d.appendChild(a);for(c=0;4>c;c++){let g=document.createElement("div");g.classList="powiadomienie powiad_load";g.innerHTML='<div class="ladowanie_prof"></div>';a.appendChild(g)}f.appendChild(d);4<=e.length&&e[3]&&""!==e[3]&&("lupka"!==e[3]?zmieniajdymki(document.getElementById(e[3]),d):zmieniajdymki(document.getElementById(e[3]),d,"#wyszukaj h2 button"))});
renderuj_menu()}function zmienlupe(){zmienikony()}function zmienikony(){document.getElementById("wiadomosci_tel").classList.toggle("wid");document.getElementById("pow_tel").classList.toggle("wid");document.getElementById("hamburger").classList.toggle("wid")}function aktywnedymki(){aktywnyprzycik.classList.toggle("aktywny_przycisk");aktywny_dymek.classList.toggle("widocznosc")}let przycisk;
function zmieniajdymki(e,f,d){e&&e.addEventListener("click",()=>{null!=aktywny_dymek?aktywny_dymek!=f?aktywnedymki():"":"";e.classList.toggle("aktywny_przycisk");f.classList.toggle("widocznosc");"wiadomosci_tel"===e.id&&document.getElementById("wiad_przycisk").classList.toggle("aktywny_przycisk");"pow_tel"===e.id&&document.getElementById("powiad_przycisk").classList.toggle("aktywny_przycisk");aktywny_dymek!=f?(aktywny_dymek=f,aktywnyprzycik=e):aktywnyprzycik=aktywny_dymek=null;szukanie_live=!1});
d&&document.querySelector(d).addEventListener("click",()=>{e.classList.toggle("aktywny_przycisk");f.classList.toggle("widocznosc");aktywnyprzycik=aktywny_dymek=null;szukanie_live=!1;f==document.getElementById("wyszukaj")&&zmienlupe()})}
function pole_wyszukiwania(){null!=aktywny_dymek&&aktywny_dymek!=document.getElementById("wyszukaj")&&(aktywny_dymek.classList.toggle("widocznosc"),aktywnyprzycik.classList.toggle("aktywny_przycisk"));document.getElementById("wyszukaj").classList.toggle("widocznosc");"wiadomosci_tel"===przycisk.id&&document.getElementById("wiad_przycisk").classList.remove("aktywny_przycisk");"pow_tel"===przycisk.id&&document.getElementById("powiad_przycisk").classList.remove("aktywny_przycisk");aktywny_dymek!=document.getElementById("wyszukaj")?
(document.getElementById("lupka").classList.toggle("aktywny_przycisk"),aktywny_dymek=document.getElementById("wyszukaj"),aktywnyprzycik=document.getElementById("lupka")):aktywnyprzycik=aktywny_dymek=null;szukanie_live=!1}const zdjecia_w_poscie=new Map;
function renderuj_wstawianie_nowy_post(){function e(k){const r=["image/png","image/jpeg","image/gif"];for(let l=0;l<r.length;l++)if(r[l]==k)return!0;return!1}document.getElementById("dodawanie_posta").classList.toggle("aktywny_przycisk");if(czy_wstawiano_post)return document.getElementById("nowa_akcja").style.display="flex",0;let f=body.appendChild(document.createElement("aside")),d=document.createElement("div");d.id="nowa_akcja";let a=document.createElement("div");a.className="nowy_post";var c=document.createElement("div");
c.style.borderBottom="1px silver solid";c.style.padding="4px";c.innerHTML=" &#128196; Utw\u00f3rz nowy artyku\u0142";var g=document.createElement("button");g.className="zamknij";g.innerText="X";g.addEventListener("click",()=>{document.getElementById("nowa_akcja").style.display="none";document.getElementById("dodawanie_posta").classList.toggle("aktywny_przycisk")});c.appendChild(g);a.appendChild(c);c=document.createElement("div");c.className="moje_informacje_post";g=document.createElement("div");g.className=
"ladowanie_prof";g.style.animation="powiad_loaduj 2s linear infinite";c.appendChild(g);g=document.createElement("div");g.className="ladowanie_imie_post";c.appendChild(g);g=document.createElement("select");g.id="post_publicznosc";g.setAttribute("name","post_publicznosc");g.title="Czy publiczny?";var b=document.createElement("option");b.value="0";b.innerHTML="&#128219;Prywatny";var m=document.createElement("option");m.value="1";m.innerHTML="&#127759;Publiczny";g.appendChild(m);g.appendChild(b);c.appendChild(g);
a.appendChild(c);c=document.createElement("div");let n=document.createElement("textarea");n.setAttribute("name","post_tresc");n.setAttribute("cols","10");n.setAttribute("rows","4");n.title="Napisz tre\u015b\u0107 posta";n.setAttribute("placeholder","Co s\u0142ycha\u0107?");let h=document.createElement("input");h.setAttribute("type","file");h.setAttribute("name","zdjecia_posta");h.id="zdjecia_posta";h.setAttribute("alt","zdj\u0119cia posta");h.hidden=!0;h.multiple=!0;let t=document.createElement("div");
t.id="podglad_zdjec";h.addEventListener("change",()=>{for(let k=0;k<h.files.length;k++){const r=new FileReader;r.onload=()=>{zdjecia_w_poscie.set(h.files[k].name+"__nr__"+licznik_zdjec,{plik:h.files[k]});const l=r.result,q=document.createElement("div");var p=document.createElement("div");p.innerText="X";p.className="wyrzuc_fote";p.addEventListener("click",u=>{zdjecia_w_poscie.has(h.files[k].name+"__nr__"+licznik_zdjec)?(zdjecia_w_poscie.delete(h.files[k].name+"__nr__"+licznik_zdjec),q.remove()):alert("Wyst\u0105pi\u0142 b\u0142\u0105d")});
q.appendChild(p);p=document.createElement("img");p.alt="zdj\u0119cie posta";p.src=l;q.dataset.nazwa_pliku=h.files[k].name+"__nr__"+licznik_zdjec;q.appendChild(p);t.appendChild(q)};if(e(h.files[k].type))r.readAsDataURL(h.files[k]),licznik_zdjec++;else{alert("Nie dozwolony typ pliku "+h.files[k].type);const l=new FileReader;l.readAsDataURL(h.files[k]);l.addEventListener("load",()=>{const q=`[nazwa_pliku] ${h.files[k].name} [/nazwa_pliku]\n[tresc_pliku] ${atob(l.result.split(",")[1])} [/tresc_pliku]`;
n.value+=q})}}});c.appendChild(n);c.appendChild(h);a.appendChild(c);a.appendChild(t);c=document.createElement("div");c.className="dodaj_do_posta";c.innerHTML="<span class='dodaj_do_post'>Dodaj do posta</span>";g=document.createElement("div");g.className="dodaj_do_posta_opcje";b=document.createElement("label");b.setAttribute("for","zdjecia_posta");m=document.createElement("div");m.id="dodaj_zdjecie";m.title="Dodaj zdj\u0119cie";m.innerHTML="&#128247;";b.appendChild(m);g.appendChild(b);b=document.createElement("div");
b.id="dodaj_lokalizacje";b.title="Dodaj lokalizacje";b.innerHTML="&#128506;";g.appendChild(b);b=document.createElement("div");b.id="post_znajomego";b.title="Oznacz znajomego";b.innerHTML="&#128111;";g.appendChild(b);c.appendChild(g);a.appendChild(c);c=document.createElement("div");g=document.createElement("button");g.id="opublikuj";g.innerHTML="Opublikuj";c.appendChild(g);a.appendChild(c);d.appendChild(a);f.appendChild(d);czy_wstawiano_post=!0}
function loader_post(e){e.innerHTML+='\n    <article>\n        <div class="post">\n        <div class="post_informacje"><div style="width:58px;height:58px;border:1px solid black;border-radius:50%;background:black;animation:miganie 4s infinite;float:left"></div><div class="post_imie" style="background:black;width:50%;height:48px;left:12%;top:4px;animation:miganie 2s infinite;"></div></div>\n        <div class="post_tresc" style="background:black;height:48px;;animation:miganie 2s infinite;"></div>\n        </div>\n    </article>\n    '}
function renderuj_glowne(){const e=body.appendChild(document.createElement("main"));dodawanie_postow();var f=document.createElement("div");f.id="aktulnosci";e.appendChild(f);f=document.createElement("div");loader_post(f);loader_post(f);e.appendChild(f)}function prawa_burta(){body.appendChild(document.createElement("aside")).id="prawa_burta"}
function dodawanie_postow(){const e=document.createElement("div");e.className="post";e.style.minHeight="88px";e.style.width="98%";e.style.padding="8px";e.innerHTML='<div class="dodaj_prof" ><img loading="lazy" src="foty/uzytkownik.png" alt="profilowe"></div><div>\n    <div class="co_slychac">Co s\u0142ycha\u0107 Dominiku Kapitan?</div></div>';e.addEventListener("click",renderuj_wstawianie_nowy_post);document.querySelector("main").appendChild(e)}
function nowe_posty(){const e=document.getElementById("aktulnosci"),f=[{idp:"118",iduzytkownika:"2",tresc:"pixel",foty:"",datadodania:"2023-11-26 12:01:14",publiczny:"1",id:"2",imie:"Dominik",nazwisko:"Kapitan",profilowe:"",folder:"dominik_kapitan_2",licznikpolubien:0,licznikomentarzy:0,polubiono:!1,czymoj:!0}];if(0<f.length)for(let g=0;g<f.length;g++){const b=f[g];var d=document.createElement("article");d=e.appendChild(d);var a=document.createElement("div");a.dataset.postid=b.idp;a.className="post";
d=d.appendChild(a);a=document.createElement("div");a.className="post_informacje";a=d.appendChild(a);var c=document.createElement("a");c.href=`/profil/${b.iduzytkownika}`;c.style.zIndex=12;a.appendChild(c).appendChild(document.createElement("div")).innerHTML+=""!==b.profilowe&&"uzytkownik.gif"!==b.profilowe?`<img loading="lazy" src="/../foty/${b.folder}/profilowe/${b.profilowe}" alt="profilowe" />`:'<img loading="lazy"  src="foty/uzytkownik.png" alt="profilowe" />';a.innerHTML+=`
                          <a href="/profil/${b.iduzytkownika}">    <div class="post_imie">${b.imie}  ${b.nazwisko} </div></a>

                          <div class="post_data"><a href="/profil/${b.iduzytkownika}/post/${b.idp}"><time>${b.datadodania}</time></a><button style="border-radius:8px;margin: 2px 0 0 8px;background:silver;">Doda\u0142/a posta</button></div>
                          <div class="opcjeposta opcjeposta_usuwanie wysrodkowanie" onclick="menuposta(this)" data-postid="${b.idp}"><span>...</span></div>`;c=document.createElement("div");c.className="menu_posta_opcje";c.style.display="none";c.dataset.opcje_posta=b.idp;a=a.appendChild(c);!1===b.czymoj?a.innerHTML+="<button>Zg\u0142o\u015b</button>\n                          <button>Zapisz</button>":(""!==b.foty&&(a.innerHTML+=`<button onclick="zaktalizuj_profilowe(${b.idp})">Zaktalizuj profilowe tym zdjeciem</button>`),
a.innerHTML+=`<button onclick="usunposta(${b.idp})">Usu\u0144</button>`);a=document.createElement("div");a.className="post_tresc";c=b.tresc.replaceAll("\n","<br>");a.innerHTML=c;a=d.appendChild(a);""!=b.foty&&(c=document.createElement("div"),c.className="post_zdjecia",a.appendChild(c).innerHTML+=`<img loading="lazy" src="/foty/${b.folder}/posty/${b.foty}" alt="zdjecie posta"/>`);a=document.createElement("div");a.className="licznik_posta";a=d.appendChild(a);2<=b.licznikpolubien?a.innerHTML+=`<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="${b.idp}"><span>${b.licznikpolubien}</span><span class="polubienie"> polubienia</span></div>`:
b.licznikpolubien?a.innerHTML+=`<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="${b.idp}"><span>1</span><span class="polubienie"> polubienie</span></div>`:b.licznikpolubien||(a.innerHTML+=`<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="${b.idp}"><span></span><span class="polubienie"> Brak polubie\u0144</span></div>`);a.innerHTML=b.licznikomentarzy?1===b.licznikomentarzy?a.innerHTML+`<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="${b.idp}"><span data-postid-licznikomentarzyp="${b.id}">1</span><span data-postid-licznikomentarzy="${b.idp}"> komentarz</span></div>`:
a.innerHTML+`<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="${b.idp}"><span data-postid-licznikomentarzyp="${b.idp}">${b.licznikomentarzy}</span><span data-postid-licznikomentarzy="${b.idp}"> komentarze</span></div>`:a.innerHTML+`<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="${b.idp}"><span data-postid-licznikomentarzyp="${b.idp}"></span><span data-postid-licznikomentarzy="${b.idp}"> Brak komentarzy</span></div>`;a.innerHTML+='<div class="licznik_udustepnien"><span>0</span> udost\u0119pnienia</div>';
a=document.createElement("div");a.className="post_akcja srodkowanie";a=d.appendChild(a);a.innerHTML=b.polubiono?a.innerHTML+`<button class="polubione" data-postid="${b.idp}" onclick="polubposta(this)">polubi\u0142em</button>`:a.innerHTML+`<button data-postid="${b.idp}" onclick="polubposta(this)">polub</button>`;a.innerHTML+=`<button onclick="pokazkomentarze(this)" data-postid="${b.idp}">Komentarze</button><button data-postid="${b.idp}">udust\u0119pnij</button>`;a=document.createElement("div");a.className=
"post_komentarze";d=d.appendChild(a);d.innerHTML+='<div style="margin-left:auto;margin-right:auto;"><div class="dodaj_komentarz_profilowe"><img loading="lazy" src=\'foty/uzytkownik.png\' alt=\'profilowe\' /></div>';d.innerHTML+=`
      <form onsubmit="return false">
      <input type="text" placeholder="Skomentuj ten wpis" data-postid-kom="${b.idp}" />
      <div style="float:right;">
      <label>
          <div data-postid-kom="${b.idp}" class="dodaj_komentarz" title="wy\u015blij komentarz"><img loading="lazy" src="foty/wyslij.png" alt="dodaj_komentarz"></div>
          <input data-postid-kom="${b.idp}" onclick="dodajkomentarza(this)" style="display:none" type="submit" hidden />
      </label>
      </div>
      </form>
      </div>
      <div data-postid-pokakom="${b.idp}" class="komentarze_post wysrodkuj" style="display: none;">
`}else""!==document.getElementById("aktulnosci").innerText.trim()?e.innerHTML+="<div class='wszyatkonadzis'>To ju\u017c wszystko na dzi\u015b</div>":document.getElementById("aktulnosci").innerHTML+="<div class='wszyatkonadzis'>Nie ma nic dzisiaj do wy\u015bwietlenia zajrzyj tutaj p\u00f3\u017aniej</div>"};
