'use strict';"strict mode";const l=document.querySelector("body"),r=document.getElementById("ladowanie");document.getElementById("tytul_portalu");document.getElementById("lupka");document.getElementById("wyszukiwarka");document.getElementById("powiad_przycisk");document.getElementById("powiad");document.getElementById("pilne_przycisk");document.getElementById("pilne_wiad");document.getElementById("wiad_przycisk");document.getElementById("wiadomosci");let t=null,u=null;document.getElementById("wiadomosci_tel");
document.getElementById("pow_tel");document.getElementById("wyszukaj");let w=!1,y=!1,z=0;
window.onload=()=>{B();var g=l.appendChild(document.createElement("main")),e=document.createElement("div");e.className="post";e.style.minHeight="88px";e.style.width="98%";e.style.padding="8px";e.innerHTML='<div class="dodaj_prof" ><img loading="lazy" src="foty/uzytkownik.png" alt="profilowe"></div><div>\n    <div class="co_slychac">Co s\u0142ycha\u0107 Dominiku Kapitan?</div></div>';e.addEventListener("click",C);document.querySelector("main").appendChild(e);e=document.createElement("div");e.id="aktulnosci";
g.appendChild(e);e=document.createElement("div");D(e);D(e);g.appendChild(e);l.appendChild(document.createElement("aside")).id="prawa_burta";l.removeChild(r);g=document.getElementById("aktulnosci");e=[{idp:"118",iduzytkownika:"2",tresc:"pixel",foty:"",datadodania:"2023-11-26 12:01:14",publiczny:"1",id:"2",imie:"Dominik",nazwisko:"Kapitan",profilowe:"",folder:"dominik_kapitan_2",licznikpolubien:0,licznikomentarzy:0,polubiono:!1,czymoj:!0}];if(0<e.length)for(let f=0;f<e.length;f++){const b=e[f];var d=
g.appendChild(document.createElement("article")),a=document.createElement("div");a.dataset.G=b.g;a.className="post";d=d.appendChild(a);a=document.createElement("div");a.className="post_informacje";a=d.appendChild(a);var c=document.createElement("a");c.href=`/profil/${b.j}`;c.style.zIndex=12;a.appendChild(c).appendChild(document.createElement("div")).innerHTML+=""!==b.m&&"uzytkownik.gif"!==b.m?`<img loading="lazy" src="/../foty/${b.o}/profilowe/${b.m}" alt="profilowe" />`:'<img loading="lazy"  src="foty/uzytkownik.png" alt="profilowe" />';
a.innerHTML+=`
                          <a href="/profil/${b.j}">    <div class="post_imie">${b.v}  ${b.B} </div></a>

                          <div class="post_data"><a href="/profil/${b.j}/post/${b.g}"><time>${b.u}</time></a><button style="border-radius:8px;margin: 2px 0 0 8px;background:silver;">Doda\u0142/a posta</button></div>
                          <div class="opcjeposta opcjeposta_usuwanie wysrodkowanie" onclick="menuposta(this)" data-postid="${b.g}"><span>...</span></div>`;c=document.createElement("div");c.className="menu_posta_opcje";c.style.display="none";c.dataset.C=b.g;a=a.appendChild(c);!1===b.s?a.innerHTML+="<button>Zg\u0142o\u015b</button>\n                          <button>Zapisz</button>":(""!==b.i&&(a.innerHTML+=`<button onclick="zaktalizuj_profilowe(${b.g})">Zaktalizuj profilowe tym zdjeciem</button>`),
a.innerHTML+=`<button onclick="usunposta(${b.g})">Usu\u0144</button>`);a=document.createElement("div");a.className="post_tresc";c=b.H.replaceAll("\n","<br>");a.innerHTML=c;a=d.appendChild(a);""!=b.i&&(c=document.createElement("div"),c.className="post_zdjecia",a.appendChild(c).innerHTML+=`<img loading="lazy" src="/foty/${b.o}/posty/${b.i}" alt="zdjecie posta"/>`);a=document.createElement("div");a.className="licznik_posta";a=d.appendChild(a);2<=b.h?a.innerHTML+=`<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="${b.g}"><span>${b.h}</span><span class="polubienie"> polubienia</span></div>`:
b.h?a.innerHTML+=`<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="${b.g}"><span>1</span><span class="polubienie"> polubienie</span></div>`:b.h||(a.innerHTML+=`<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="${b.g}"><span></span><span class="polubienie"> Brak polubie\u0144</span></div>`);a.innerHTML=b.l?1===b.l?a.innerHTML+`<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="${b.g}"><span data-postid-licznikomentarzyp="${b.id}">1</span><span data-postid-licznikomentarzy="${b.g}"> komentarz</span></div>`:
a.innerHTML+`<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="${b.g}"><span data-postid-licznikomentarzyp="${b.g}">${b.l}</span><span data-postid-licznikomentarzy="${b.g}"> komentarze</span></div>`:a.innerHTML+`<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="${b.g}"><span data-postid-licznikomentarzyp="${b.g}"></span><span data-postid-licznikomentarzy="${b.g}"> Brak komentarzy</span></div>`;a.innerHTML+='<div class="licznik_udustepnien"><span>0</span> udost\u0119pnienia</div>';
a=document.createElement("div");a.className="post_akcja srodkowanie";a=d.appendChild(a);a.innerHTML=b.F?a.innerHTML+`<button class="polubione" data-postid="${b.g}" onclick="polubposta(this)">polubi\u0142em</button>`:a.innerHTML+`<button data-postid="${b.g}" onclick="polubposta(this)">polub</button>`;a.innerHTML+=`<button onclick="pokazkomentarze(this)" data-postid="${b.g}">Komentarze</button><button data-postid="${b.g}">udust\u0119pnij</button>`;a=document.createElement("div");a.className="post_komentarze";
d=d.appendChild(a);d.innerHTML+='<div style="margin-left:auto;margin-right:auto;"><div class="dodaj_komentarz_profilowe"><img loading="lazy" src=\'foty/uzytkownik.png\' alt=\'profilowe\' /></div>';d.innerHTML+=`
      <form onsubmit="return false">
      <input type="text" placeholder="Skomentuj ten wpis" data-postid-kom="${b.g}" />
      <div style="float:right;">
      <label>
          <div data-postid-kom="${b.g}" class="dodaj_komentarz" title="wy\u015blij komentarz"><img loading="lazy" src="foty/wyslij.png" alt="dodaj_komentarz"></div>
          <input data-postid-kom="${b.g}" onclick="dodajkomentarza(this)" style="display:none" type="submit" hidden />
      </label>
      </div>
      </form>
      </div>
      <div data-postid-pokakom="${b.g}" class="komentarze_post wysrodkuj" style="display: none;">
`}else""!==document.getElementById("aktulnosci").innerText.trim()?g.innerHTML+="<div class='wszyatkonadzis'>To ju\u017c wszystko na dzi\u015b</div>":document.getElementById("aktulnosci").innerHTML+="<div class='wszyatkonadzis'>Nie ma nic dzisiaj do wy\u015bwietlenia zajrzyj tutaj p\u00f3\u017aniej</div>"};function E(){document.location.reload()}
function B(){let g=document.createElement("nav"),e=document.createElement("div");e.className="menu";var d=document.createElement("header");d.id="tytul_portalu";d.innerHTML="<h1>Pixi</h1>";d.addEventListener("click",E);e.appendChild(d);d=document.createElement("div");d.classList="wyszukaj i";var a=document.createElement("form");a.setAttribute("method","POST");a.className="i";var c=document.createElement("input");c.setAttribute("type","text");c.className="b";c.setAttribute("name","wyszukiwarka");c.id=
"wyszukiwarka";c.setAttribute("placeholder","Szukaj w pixi");c.addEventListener("focus",()=>{w||(943<=window.innerWidth&&(w?"":(null!=t&&t!=document.getElementById("wyszukaj")&&(t.classList.toggle("widocznosc"),u.classList.toggle("aktywny_przycisk")),document.getElementById("wyszukaj").classList.toggle("widocznosc"),"wiadomosci_tel"===F.id&&document.getElementById("wiad_przycisk").classList.remove("aktywny_przycisk"),"pow_tel"===F.id&&document.getElementById("powiad_przycisk").classList.remove("aktywny_przycisk"),
t!=document.getElementById("wyszukaj")?(document.getElementById("lupka").classList.toggle("aktywny_przycisk"),t=document.getElementById("wyszukaj"),u=document.getElementById("lupka")):u=t=null,w=!1)),w=!0)});a.appendChild(c);d.appendChild(a);e.appendChild(d);a=document.createElement("button");a.id="lupka";a.innerHTML="&#128270;";d.appendChild(a);d=document.createElement("div");d.className="telefon";a=document.createElement("button");a.id="wiadomosci_tel";a.className="wiadomosci_ikonka";a.setAttribute("alt",
"wiadomosci");a.innerHTML="&#128232;";c=document.createElement("div");c.className="licznik_menu";c.innerText="488";a.appendChild(c);d.appendChild(a);a=document.createElement("div");a.id="pow_tel";a.style.left="48%";a.className="wiadomosci_ikonka";a.innerHTML="&#128240;";c=document.createElement("div");c.className="licznik_menu";c.innerText="488";a.appendChild(c);d.appendChild(a);a=document.createElement("div");a.appendChild(document.createElement("div"));a.appendChild(document.createElement("div"));
a.appendChild(document.createElement("div"));a.id="hamburger";a.addEventListener("click",()=>{document.querySelector(".komputer").classList.toggle("widocznoscz")});d.appendChild(a);e.appendChild(d);d=document.createElement("div");d.className="komputer";a=document.createElement("div");a.className="menu_opcje";c=document.createElement("div");c.innerHTML="X";c.style.background="none";c.style.fontSize="48px";c.style.margin="24px";c.className="zamknij";c.addEventListener("click",()=>{document.querySelector(".komputer").classList.toggle("widocznoscz")});
a.appendChild(c);d.appendChild(a);e.appendChild(d);g.appendChild(e);l.appendChild(g);G()}
function H(){let g=document.querySelector(".menu_opcje");[["aktywny_przycisk","Strona g\u0142\u00f3wna"],["powiad_przycisk","Powiadomienia","powiadomienia"],["wiad_przycisk","Wiadomo\u015bci","wiadomosci"],["dodawanie_posta","Dodaj artyku\u0142"],[" ","M\u00f3j profil"],[" ","Ustawienia"],[" ","Wi\u0119cej"],[" ","Wyloguj"]].forEach(e=>{const d=document.createElement("button");d.id=e[0];d.innerText=e[1];3<=e.length&&e[2]&&(I(d,document.getElementById(e[2]),"#"+e[2]+" h2 button"),e=document.createElement("div"),
e.className="licznik_menu",e.innerText="488",d.appendChild(e));g.appendChild(d)});document.getElementById("dodawanie_posta").addEventListener("click",C)}
function G(){[["powiadomienia","powiad","Moje powiadomienia","pow_tel"],["wiadomosci","pilne_wiadom","Wiadomo\u015bci","wiadomosci_tel"],["wyszukaj","wynik_wyszuk","Wyniki wyszukiwania","lupka"]].forEach(g=>{let e=l.appendChild(document.createElement("aside")),d=document.createElement("div");d.id=g[0];d.classList="powiadomienia";var a=document.createElement("h2");"wyszukaj"!=g[0]?a.innerText=g[2]+" :":(a.className="border_none",d.innerHTML='\n        <form method="POST" class="i"><input type="text" class="wyszukuwanie" name="wyszukiwarka" id="wyszukiwark" placeholder="Szukaj w pixi"></form>\n        ');
var c=document.createElement("button");c.innerText="X";a.appendChild(c);d.appendChild(a);a=document.createElement("div");a.classList="powiad";a.id=g[1];d.appendChild(a);for(c=0;4>c;c++){let f=document.createElement("div");f.classList="powiadomienie powiad_load";f.innerHTML='<div class="ladowanie_prof"></div>';a.appendChild(f)}e.appendChild(d);4<=g.length&&g[3]&&""!==g[3]&&("lupka"!==g[3]?I(document.getElementById(g[3]),d):I(document.getElementById(g[3]),d,"#wyszukaj h2 button"))});H()}let F;
function I(g,e,d){g&&g.addEventListener("click",()=>{null!=t?t!=e?(u.classList.toggle("aktywny_przycisk"),t.classList.toggle("widocznosc")):"":"";g.classList.toggle("aktywny_przycisk");e.classList.toggle("widocznosc");"wiadomosci_tel"===g.id&&document.getElementById("wiad_przycisk").classList.toggle("aktywny_przycisk");"pow_tel"===g.id&&document.getElementById("powiad_przycisk").classList.toggle("aktywny_przycisk");t!=e?(t=e,u=g):u=t=null;w=!1});d&&document.querySelector(d).addEventListener("click",
()=>{g.classList.toggle("aktywny_przycisk");e.classList.toggle("widocznosc");u=t=null;w=!1;e==document.getElementById("wyszukaj")&&(document.getElementById("wiadomosci_tel").classList.toggle("wid"),document.getElementById("pow_tel").classList.toggle("wid"),document.getElementById("hamburger").classList.toggle("wid"))})}const J=new Map;
function C(){function g(k){const v=["image/png","image/jpeg","image/gif"];for(let m=0;m<v.length;m++)if(v[m]==k)return!0;return!1}document.getElementById("dodawanie_posta").classList.toggle("aktywny_przycisk");if(y)return document.getElementById("nowa_akcja").style.display="flex",0;let e=l.appendChild(document.createElement("aside")),d=document.createElement("div");d.id="nowa_akcja";let a=document.createElement("div");a.className="nowy_post";var c=document.createElement("div");c.style.borderBottom=
"1px silver solid";c.style.padding="4px";c.innerHTML=" &#128196; Utw\u00f3rz nowy artyku\u0142";var f=document.createElement("button");f.className="zamknij";f.innerText="X";f.addEventListener("click",()=>{document.getElementById("nowa_akcja").style.display="none";document.getElementById("dodawanie_posta").classList.toggle("aktywny_przycisk")});c.appendChild(f);a.appendChild(c);c=document.createElement("div");c.className="moje_informacje_post";f=document.createElement("div");f.className="ladowanie_prof";
f.style.animation="powiad_loaduj 2s linear infinite";c.appendChild(f);f=document.createElement("div");f.className="ladowanie_imie_post";c.appendChild(f);f=document.createElement("select");f.id="post_publicznosc";f.setAttribute("name","post_publicznosc");f.title="Czy publiczny?";var b=document.createElement("option");b.value="0";b.innerHTML="&#128219;Prywatny";var n=document.createElement("option");n.value="1";n.innerHTML="&#127759;Publiczny";f.appendChild(n);f.appendChild(b);c.appendChild(f);a.appendChild(c);
c=document.createElement("div");let p=document.createElement("textarea");p.setAttribute("name","post_tresc");p.setAttribute("cols","10");p.setAttribute("rows","4");p.title="Napisz tre\u015b\u0107 posta";p.setAttribute("placeholder","Co s\u0142ycha\u0107?");let h=document.createElement("input");h.setAttribute("type","file");h.setAttribute("name","zdjecia_posta");h.id="zdjecia_posta";h.setAttribute("alt","zdj\u0119cia posta");h.hidden=!0;h.multiple=!0;let A=document.createElement("div");A.id="podglad_zdjec";
h.addEventListener("change",()=>{for(let k=0;k<h.files.length;k++){const v=new FileReader;v.onload=()=>{J.set(h.files[k].name+"__nr__"+z,{D:h.files[k]});const m=v.result,x=document.createElement("div");var q=document.createElement("div");q.innerText="X";q.className="wyrzuc_fote";q.addEventListener("click",()=>{J.has(h.files[k].name+"__nr__"+z)?(J.delete(h.files[k].name+"__nr__"+z),x.remove()):alert("Wyst\u0105pi\u0142 b\u0142\u0105d")});x.appendChild(q);q=document.createElement("img");q.alt="zdj\u0119cie posta";
q.src=m;x.dataset.A=h.files[k].name+"__nr__"+z;x.appendChild(q);A.appendChild(x)};if(g(h.files[k].type))v.readAsDataURL(h.files[k]),z++;else{alert("Nie dozwolony typ pliku "+h.files[k].type);const m=new FileReader;m.readAsDataURL(h.files[k]);m.addEventListener("load",()=>{p.value+=`[nazwa_pliku] ${h.files[k].name} [/nazwa_pliku]\n[tresc_pliku] ${atob(m.result.split(",")[1])} [/tresc_pliku]`})}}});c.appendChild(p);c.appendChild(h);a.appendChild(c);a.appendChild(A);c=document.createElement("div");c.className=
"dodaj_do_posta";c.innerHTML="<span class='dodaj_do_post'>Dodaj do posta</span>";f=document.createElement("div");f.className="dodaj_do_posta_opcje";b=document.createElement("label");b.setAttribute("for","zdjecia_posta");n=document.createElement("div");n.id="dodaj_zdjecie";n.title="Dodaj zdj\u0119cie";n.innerHTML="&#128247;";b.appendChild(n);f.appendChild(b);b=document.createElement("div");b.id="dodaj_lokalizacje";b.title="Dodaj lokalizacje";b.innerHTML="&#128506;";f.appendChild(b);b=document.createElement("div");
b.id="post_znajomego";b.title="Oznacz znajomego";b.innerHTML="&#128111;";f.appendChild(b);c.appendChild(f);a.appendChild(c);c=document.createElement("div");f=document.createElement("button");f.id="opublikuj";f.innerHTML="Opublikuj";c.appendChild(f);a.appendChild(c);d.appendChild(a);e.appendChild(d);y=!0}
function D(g){g.innerHTML+='\n    <article>\n        <div class="post">\n        <div class="post_informacje"><div style="width:58px;height:58px;border:1px solid black;border-radius:50%;background:black;animation:miganie 4s infinite;float:left"></div><div class="post_imie" style="background:black;width:50%;height:48px;left:12%;top:4px;animation:miganie 2s infinite;"></div></div>\n        <div class="post_tresc" style="background:black;height:48px;;animation:miganie 2s infinite;"></div>\n        </div>\n    </article>\n    '};
